### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by ranierivalenca** [lipeh777/comuniq#31]
- [ ] Compreender o mecanismo de Seed do Laravel 
- [ ] Completar o esquema do banco 
- [ ] Tabelas populadas via Seed (exceto chamados e observadores) 
- [ ] Mecanismo de cadastro de novos usuários integrado ao esquema de banco de dados 
- [ ] Mecanismo de autenticação 
- [ ] Cadastro de novos chamados
