### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by ranierivalenca** [lipeh777/comuniq#32]
- [ ] Tabelas populadas via Seed (exceto chamados e observadores) 
- [ ] Mecanismo de cadastro de novos usuários integrado ao esquema de banco de dados 
- [ ] Cadastro de novos chamados
- [ ] Usuários vinculados a setores podem ver os chamados de itens direcionados àquele setor 
- [ ] Listagem de chamados abertos e observados pelo usuário logado 
- [ ] C**D de observador 
- [ ] Acompanhamento de chamados (atualização da situação do chamado (tabela de status_chamado))

**Comment by ranierivalenca** [comment]
Tive que vir conferir pra ver se era verdade... faltando **dois dias** pra terminar a sprint e apenas **UMA** pessoa trabalhou, **UM DIA**!!!! Que houve?
