### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by ranierivalenca** [lipeh777/comuniq#47]
### Sprint 3
- [x] Tabelas populadas via Seed (exceto chamados e observadores) 
- [x] Mecanismo de cadastro de novos usuários integrado ao esquema de banco de dados 
- [ ] Cadastro de novos chamados

### Sprint 4
- [ ] Usuários vinculados a setores podem ver os chamados de itens direcionados àquele setor 
- [ ] Listagem de chamados abertos e observados pelo usuário logado 
- [ ] C**D de observador 
- [ ] Acompanhamento de chamados (atualização da situação do chamado (tabela de status_chamado))
