### ISSUE TITLE
Sprint 8

### ISSUE THREAD

**Issue by ranierivalenca** [lipeh777/comuniq#67]
### Sprint 3
- [ ] Cadastro de novos chamados

### Sprint 4
- [ ] Usuários vinculados a setores podem ver os chamados de itens direcionados àquele setor 
- [ ] Listagem de chamados abertos e observados pelo usuário logado 
- [ ] C**D de observador 
- [ ] Acompanhamento de chamados (atualização da situação do chamado (tabela de status_chamado))

## Sprint 8
- [ ] Regra para um item ter apenas um chamado aberto por vez
- [ ] Implementação da regra de negócio para chamados compostos (chamados criados a partir de outros chamados)
